// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHhsHihfKyyR18IPAWDJG7c9RguXpCkJw',
    appId: '1:954356657595:web:0b7c28f86d30587b57689e',
    messagingSenderId: '954356657595',
    projectId: 'chat-app-cfcb6',
    authDomain: 'chat-app-cfcb6.firebaseapp.com',
    storageBucket: 'chat-app-cfcb6.appspot.com',
    measurementId: 'G-V4FDBFDRLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJlGLXVVxuActp0GQhlwRk_qoh9LdrtfA',
    appId: '1:954356657595:android:c2838925a524a10757689e',
    messagingSenderId: '954356657595',
    projectId: 'chat-app-cfcb6',
    storageBucket: 'chat-app-cfcb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjtbZg6WB7wqeKWFku2o8v5Cw9s0U5LA',
    appId: '1:954356657595:ios:f6a388c4e6ee227a57689e',
    messagingSenderId: '954356657595',
    projectId: 'chat-app-cfcb6',
    storageBucket: 'chat-app-cfcb6.appspot.com',
    iosBundleId: 'com.example.chatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFjtbZg6WB7wqeKWFku2o8v5Cw9s0U5LA',
    appId: '1:954356657595:ios:f6a388c4e6ee227a57689e',
    messagingSenderId: '954356657595',
    projectId: 'chat-app-cfcb6',
    storageBucket: 'chat-app-cfcb6.appspot.com',
    iosBundleId: 'com.example.chatsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHhsHihfKyyR18IPAWDJG7c9RguXpCkJw',
    appId: '1:954356657595:web:65b308dd9959c74857689e',
    messagingSenderId: '954356657595',
    projectId: 'chat-app-cfcb6',
    authDomain: 'chat-app-cfcb6.firebaseapp.com',
    storageBucket: 'chat-app-cfcb6.appspot.com',
    measurementId: 'G-S80626L37K',
  );

}